#!/usr/bin/env bash
inotifywait -e close_write,moved_to,create -m . |
while read -r directory events filename; do
  if [ "$filename" = "water.log" ]; then
    tail -n1 water.log | xargs ./update
  fi
done
